services:
  postgres:
    image: postgres:latest
    container_name: diplomado
    restart: always
    ports:
      - '5432:5432'
    networks:
      postgres:
        aliases:
          - postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=diplomado
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - '5050:80'
    networks:
      - postgres
    depends_on:
      - postgres
    volumes:
      - pgadmin4_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin4_data:

networks:
  mysql:
  postgres:
